In [57]:
import numpy as np
import pandas as pd
#create arrray
data=np.array([[3,7],[-4,-6],[1,-1],[7,8],[-4,-1],[-3,-7]])
dataframe=pd.DataFrame(data,columns=['x1','x2'])


In [58]:
dataframe

x1  x2
0   3   7
1  -4  -6
2   1  -1
3   7   8
4  -4  -1
5  -3  -7

In [59]:
dataframe.describe()

x1        x2
count  6.000000  6.000000
mean   0.000000  0.000000
std    4.472136  6.324555
min   -4.000000 -7.000000
25%   -3.750000 -4.750000
50%   -1.000000 -1.000000
75%    2.500000  5.000000
max    7.000000  8.000000

In [60]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
datascaled=scaler.fit_transform(data)
dataframe=pd.DataFrame(datascaled)
dataframe.describe()

0         1
count  6.000000e+00  6.000000
mean   1.850372e-17  0.000000
std    1.095445e+00  1.095445
min   -9.797959e-01 -1.212436
25%   -9.185587e-01 -0.822724
50%   -2.449490e-01 -0.173205
75%    6.123724e-01  0.866025
max    1.714643e+00  1.385641

In [61]:
dataframe=pd.DataFrame(datascaled,columns=['x1','x2'])
dataframe.describe()

x1        x2
count  6.000000e+00  6.000000
mean   1.850372e-17  0.000000
std    1.095445e+00  1.095445
min   -9.797959e-01 -1.212436
25%   -9.185587e-01 -0.822724
50%   -2.449490e-01 -0.173205
75%    6.123724e-01  0.866025
max    1.714643e+00  1.385641

In [62]:
cov_matrix=dataframe.T @ dataframe / 5
cov_matrix

x1       x2
x1  1.20000  1.06066
x2  1.06066  1.20000

In [63]:
# eigun val eigon vec
eigenvalue , eigenvector = np.linalg.eig(cov_matrix)
eigenvalue

array([2.26066017, 0.13933983])

In [64]:
pc1=dataframe@ eigenvector[:,0]
pc2=dataframe@ eigenvector[:,1]
pc1

0    1.376937
1   -1.427667
2    0.050731
3    2.192231
4   -0.815295
5   -1.376937
dtype: float64

In [65]:
pc2

0    0.337706
1   -0.042027
2   -0.295680
3   -0.232640
4    0.570346
5   -0.337706
dtype: float64

In [66]:
data=pd.read_csv('diabetes.csv')
data.head()

data.describe

<bound method NDFrame.describe of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627  

In [67]:
data=data.drop(columns=['Outcome'], axis=1)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
datascaled=scaler.fit_transform(data)
datascaled=pd.DataFrame(datascaled)
datascaled.describe()

0             1             2             3             4  \
count  7.680000e+02  7.680000e+02  7.680000e+02  7.680000e+02  7.680000e+02   
mean  -6.476301e-17 -9.251859e-18  1.503427e-17  1.006140e-16 -3.006854e-17   
std    1.000652e+00  1.000652e+00  1.000652e+00  1.000652e+00  1.000652e+00   
min   -1.141852e+00 -3.783654e+00 -3.572597e+00 -1.288212e+00 -6.928906e-01   
25%   -8.448851e-01 -6.852363e-01 -3.673367e-01 -1.288212e+00 -6.928906e-01   
50%   -2.509521e-01 -1.218877e-01  1.496408e-01  1.545332e-01 -4.280622e-01   
75%    6.399473e-01  6.057709e-01  5.632228e-01  7.190857e-01  4.120079e-01   
max    3.906578e+00  2.444478e+00  2.734528e+00  4.921866e+00  6.652839e+00   

                  5             6             7  
count  7.680000e+02  7.680000e+02  7.680000e+02  
mean   2.590520e-16  2.451743e-16  1.931325e-16  
std    1.000652e+00  1.000652e+00  1.000652e+00  
min   -4.060474e+00 -1.189553e+00 -1.041549e+00  
25%   -5.955785e-01 -6.889685e-01 -7.862862e-01  
50%    9.419788e-04 -3.001282e-01 -3.608474e-01  
75%    5.847705e-01  4.662269e-01  6.602056e-01  
max    4.455807e+00  5.883565e+00  4.063716e+00

In [68]:
cov_matrix=datascaled.T @ datascaled / 767
cov_matrix

0         1         2         3         4         5         6  \
0  1.001304  0.129627  0.141466 -0.081778 -0.073630  0.017706 -0.033566   
1  0.129627  1.001304  0.152789  0.057403  0.331789  0.221359  0.137516   
2  0.141466  0.152789  1.001304  0.207641  0.089049  0.282173  0.041319   
3 -0.081778  0.057403  0.207641  1.001304  0.437352  0.393085  0.184167   
4 -0.073630  0.331789  0.089049  0.437352  1.001304  0.198117  0.185312   
5  0.017706  0.221359  0.282173  0.393085  0.198117  1.001304  0.140830   
6 -0.033566  0.137516  0.041319  0.184167  0.185312  0.140830  1.001304   
7  0.545051  0.263858  0.239840 -0.114119 -0.042218  0.036289  0.033605   

          7  
0  0.545051  
1  0.263858  
2  0.239840  
3 -0.114119  
4 -0.042218  
5  0.036289  
6  0.033605  
7  1.001304

In [69]:
eigenvalue , eigenvector = np.linalg.eig(cov_matrix)
eigenvalue

array([2.09711056, 1.73346726, 0.42036353, 0.40498938, 0.68351839,
       0.76333832, 0.87667054, 1.03097228])

In [74]:
pc1=datascaled@ eigenvector[:,0]
pc2=datascaled@ eigenvector[:,1]
pc3=datascaled@ eigenvector[:,7]
pc1,pc2,pc3

(0     -1.068503
 1      1.121683
 2      0.396477
 3      1.115781
 4     -2.359334
          ...   
 763   -1.562085
 764    0.100405
 765    0.283475
 766    1.060324
 767    0.839892
 Length: 768, dtype: float64,
 0     -1.234895
 1      0.733852
 2     -1.595876
 3      1.271241
 4      2.184819
          ...   
 763   -1.923150
 764    0.614181
 765   -0.097065
 766   -0.837062
 767    1.151755
 Length: 768, dtype: float64,
 0     -0.095930
 1      0.712938
 2     -1.760678
 3      0.663729
 4     -2.963107
          ...   
 763    0.867408
 764    0.764353
 765    0.077192
 766   -0.425030
 767    1.009178
 Length: 768, dtype: float64)

In [75]:
from sklearn.decomposition import PCA
pca = PCA()
pca.fit_transform(datascaled)
pca.explained_variance_ratio_

array([0.26179749, 0.21640127, 0.12870373, 0.10944113, 0.09529305,
       0.08532855, 0.05247702, 0.05055776])

In [ ]:
import matplotlib.pyplot as plt
plt.plot(pca.explained_variance_ratio_)